language: 
    - php

php:
    - 5.6

services:
    - mysql

env:
    - WP_VERSION=4.1.10

before_script:
    - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    - mysqladmin create wp --user="root" --password=""
    - php wp-cli.phar core download --version=$WP_VERSION --force
    - php wp-cli.phar core config --dbname=wp --dbuser=root --dbpass=""
    - php wp-cli.phar core install --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=fake@asfsadfasfasf.com --skip-email

script:
    -  mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_posts;' wp
