language: 
    - php

php:
    - 5.6

services:
    - mysql

env:
    - START_VERSION=4.1.10 FIRST_UPDATE_VERSION=4.4.2 SECOND_UPDATE_VERSION=4.5.1

before_script:
    - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    - mysqladmin create wp --user="root" --password=""
    - php wp-cli.phar core download --version=$START_VERSION --force
    - php wp-cli.phar core config --dbname=wp --dbuser=root --dbpass=""
    - php wp-cli.phar core install --url=localhost --title=test --admin_user=test --admin_password=test --admin_email=fake@asfsadfasfasf.com --skip-email

script:
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_posts;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_links;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_users;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_comments;' wp
    - php wp-cli.phar core update --version=$FIRST_UPDATE_VERSION
    - php wp-cli.phar core update-db
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_posts;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_links;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_users;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_comments;' wp
    - php wp-cli.phar core update --version=$SECOND_UPDATE_VERSION
    - php wp-cli.phar core update-db
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_posts;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_links;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_users;' wp
    - mysql -uroot -h localhost -e 'SHOW FIELDS FROM wp_comments;' wp
